@startuml
object CIS
object KommServer
KommServer : ID : 0
KommServer : Name: Mirth
KommServer : Version :2.0
KommServer : OS: Windows Server 2020
KommServer : IP: 172.17.233.30
object communication_5
communication_5 : Name : MDM
communication_5 : ID : 4
communication_5 : Channel : HTTP
communication_5 : Comtype : HL7 v3
CIS --|> communication_5:null
communication_5 --|> KommServer
CIS <|-- communication_5:null
communication_5 <|-- KommServer
KommServer : ID : 0
KommServer : Name: Mirth
KommServer : Version :2.0
KommServer : OS: Windows Server 2020
KommServer : IP: 172.17.233.30
object communication_10
communication_10 : Name : ADT
communication_10 : ID : 10
communication_10 : Channel : HTTP
communication_10 : Comtype : HL7 v3
CIS --|> communication_10:null
communication_10 --|> KommServer
CIS <|-- communication_10:null
communication_10 <|-- KommServer
CIS : ID : 3
CIS : Name: Cardiobase
CIS : Version :8
CIS : OS: Windows Server 2020
CIS : IP: 172.17.233.30
@enduml