@startuml
object LIS
object KommServer
KommServer : ID : 0
KommServer : Name: Mirth
KommServer : Version :2.0
KommServer : OS: Windows Server 2020
KommServer : IP: 172.17.233.136
object communication_3
communication_3 : Name : ORM
communication_3 : ID : 2
communication_3 : Channel : HTTP
communication_3 : Comtype : HL7 v3
LIS --|> communication_3:null
communication_3 --|> KommServer
LIS <|-- communication_3:null
communication_3 <|-- KommServer
LIS : ID : 1
LIS : Name: IXSERV
LIS : Version :1,5
LIS : OS: Windows Server 2020
LIS : IP: 172.17.233.136
@enduml