@startuml
object LMS
object KommServer
KommServer : ID : 0
KommServer : Name: Mirth
KommServer : Version :2.0
KommServer : OS: Windows Server 2020
object communication_6
communication_6 : Name : ORU
communication_6 : ID : 5
communication_6 : Channel : HTTP
communication_6 : Comtype : HL7 v3
LMS --|> communication_6:null
communication_6 --|> KommServer
LMS <|-- communication_6:null
communication_6 <|-- KommServer
LMS : ID : 4
LMS : Name: OPUS::L/BIT
LMS : Version :8
LMS : OS: Windows
@enduml