@startuml
object RIS
object KommServer
KommServer : ID : 0
KommServer : Name: Mirth
KommServer : Version :2.0
KommServer : OS: Windows Server 2020
object communication_8
communication_8 : Name : ORU
communication_8 : ID : 7
communication_8 : Channel : HTTP
communication_8 : Comtype : HL7 v3
RIS --|> communication_8:null
communication_8 --|> KommServer
RIS <|-- communication_8:null
communication_8 <|-- KommServer
RIS : ID : 6
RIS : Name: Medavis
RIS : Version :6
RIS : OS: Windows
@enduml