@startuml
object KommServer
object communication_1
communication_1 : Name : MDM
communication_1 : ID : 0
object communication_2
communication_2 : Name : MDM
communication_2 : ID : 1
object communication_4
communication_4 : Name : ADT
communication_4 : ID : 3
KommServer --|> communication_1
communication_1 --|> 2
KommServer --|> communication_2
communication_2 --|> 1
KommServer --|> communication_4
communication_4 --|> 3
KommServer : ID : 0
KommServer : Name : Mirth
KommServer : Version : 2.0
KommServer : OS : Windows Server 2020
KommServer : IP : 172.17.233.138
object LIS
object communication_3
communication_3 : Name : ORM
communication_3 : ID : 2
LIS --|> communication_3
communication_3 --|> 0
LIS : ID : 1
LIS : Name : IXSERV
LIS : Version : 1,5
LIS : OS : Windows Server 2020
LIS : IP : 172.17.233.136
object CMS
CMS : ID : 2
CMS : Name : Hydmedia
CMS : Version : 15
CMS : OS : Windows Server 2020
CMS : IP : 172.17.233.60
object CIS
CIS : ID : 3
CIS : Name : Cardiobase
CIS : Version : 8
CIS : OS : Windows Server 2020
CIS : IP : 172.17.233.30
@enduml